cache: bundler
language: ruby
rvm:
  - 2.4.5
  - 2.5.6
  - 2.6.4
  - 2.7.1
  - ruby-head

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.0.gemfile